export const LOAD_MEDIAS_SUCCESS = "LOAD_MEDIAS_SUCCESS";
export const LOAD_HISTORICO_SUCCESS = "LOAD_HISTORICO_SUCCESS";
export const LOAD_ANOS_SUCCESS = "LOAD_ANOS_SUCCESS";
export const LOAD_MESES_SUCCESS = "LOAD_MESES_SUCCESS";
